### ISSUE TITLE
large download

### ISSUE THREAD

**Issue by bsunders** [signalfx/apmworkshop#9]
Step 1, substep 4 (maybe rename them to 1.x for ease of reference) 

I was already in the multipass from prev step (as most would be) so better to have a command that I just paste in. Instead I copy and paste the bash command into the mutlipass vm and it didnt work of course. TO save exiting the multipass and running it, I browse to your command and past the bit without the multipass bit and that worked.  Just would have been better to not have to do that. 

ALso the download is really big and tons of content - I assume for all the use cases. Maybe let the person know will take 15 mins  or whatever.

**Comment by slernersplunk** [comment]
i've made a note on this in the repo
